export const MenuArr = [
    '홈', 
    '추천', 
    '#채널', 
    '집들이', 
    '3D인테리어', 
    '살림수납', 
    '콜렉터블', 
    '홈스토랑', 
    '핫플레이스', 
    '육아', 
    '플랜테리어', 
    '반려동물', 
    '캠핑', 
    '이벤트'
];

export const Icons = [
    {
        ogood: 'https://image.ohou.se/i/bucketplace-v2-development/uploads/admins/thumbnail_badges/164984839473493224.png?w=256&h=256&c=c&webp=1',

    }
]

export const CategoryListArr = [
    {
        title: '오세일',
        icon: 'image/오세일.png',
        alt: '오세일',
    },
    {
        title: '오늘의딜',
        icon: 'image/오늘의딜.png',
        alt: '오늘의딜',
    },
    {
        title: '집들이',
        icon: 'image/집들이.png',
        alt: '집들이',
    },
    {
        title: '행운출첵',
        icon: 'image/행운출첵.png',
        alt: '행운출첵',
    },
    {
        title: '챌린지참여',
        icon: 'image/챌린지참여.png',
        alt: '챌린지참여',
    },
    {
        title: '크리에이터',
        icon: 'image/크리에이터.png',
        alt: '크리에이터',
    },
    {
        title: '장보기',
        icon: 'image/장보기.png',
        alt: '장보기',
    },
    {
        title: '빠른배송',
        icon: 'image/빠른배송.png',
        alt: '빠른배송',
    },
    {
        title: '리모델링',
        icon: 'image/리모델링.png',
        alt: '리모델링',
    },
    {
        title: '쉬운이사',
        icon: 'image/쉬운이사.png',
        alt: '쉬운이사',
    },
]

export const FinditemArr = [
    {
        title: '여름맞이',
        alt: '여름맞이',
        icon: 'image/finditem_summ.avif',
    },
    {
        title: '가구',
        alt: '가구',
        icon: 'image/finditem_funi.png',
    },
    {
        title: '패브릭',
        alt: '패브릭',
        icon: 'image/finditem_feb.png',
    },
    {
        title: '가전・디지털',
        alt: '가전・디지털',
        icon: 'image/finditem_digi.avif',
    },
    {
        title: '주방용품',
        alt: '주방용품',
        icon: 'image/finditem_ki.png',
    },
    {
        title: '식품',
        alt: '식품',
        icon: 'image/finditem_food.png',
    },
    {
        title: '데코・식물',
        alt: '데코・식물',
        icon: 'image/finditem_deco.png',
    },
    {
        title: '조명',
        alt: '조명',
        icon: 'image/finditem_light.png',
    },
    {
        title: '수납・정리',
        alt: '수납・정리',
        icon: 'image/finditem_sto.png',
    },
    {
        title: '생활용품',
        alt: '생활용품',
        icon: 'image/finditem_daily.png',
    },
    {
        title: '생필품',
        alt: '생필품',
        icon: 'image/finditem_nece.png',
    },
    {
        title: '유아・아동',
        alt: '유아・아동',
        icon: 'image/finditem_baby.png',
    },
    {
        title: '반려동물',
        alt: '반려동물',
        icon: 'image/finditem_pet.png',
    },
    {
        title: '캠핑・레저',
        alt: '캠핑・레저',
        icon: 'image/finditem_camp.png',
    },
    {
        title: '공구・DIY',
        alt: '공구・DIY',
        icon: 'image/finditem_diy.webp',
    },
    {
        title: '인테리어시공',
        alt: '인테리어시공',
        icon: 'image/finditem_interi.webp',
    },
    {
        title: '렌탈・구독',
        alt: '렌탈・구독',
        icon: 'image/finditem_rental.webp',
    },
    {
        title: '장보기',
        alt: '장보기',
        icon: 'image/finditem_sho.avif',
    },
    {
        title: '혼수・신혼',
        alt: '혼수・신혼',
        icon: 'image/finditem_merr.avif',
    },
]

export const TodayDealItems = [
    {
        brand: '깨끗한나라',
        title: '순수 시그니처 27m X 24롤 X 3팩',
        alt: '순수 시그니처 27m X 24롤 X 3팩',
        img: 'image/deal_clean.avif',
        price_rate: 31,
        price: 31900,
        average_score: 4.8,
        review_count: 20,
    },
    {
        brand: '웰퍼니처',
        title: '웰퍼니쳐 image/BEST 침대 / 매트리스 / 소파 / 식탁',
        alt: '웰퍼니쳐 image/BEST 침대 / 매트리스 / 소파 / 식탁',
        img: 'image/deal_well.avif',
        price_rate: 47,
        price: 229000,
        average_score: 4.8,
        review_count: 14514,
    },
    {
        brand: '아르페지아',
        title: '24SS 부드러운 먼지없는 차렵이불 및 여름 냉감 침구 할인전',
        alt: '24SS 부드러운 먼지없는 차렵이불 및 여름 냉감 침구 할인전',
        img: 'image/deal_ar.avif',
        price_rate: 73,
        price: 23500,
        average_score: 4.6,
        review_count: 3128,
    },
    {
        brand: '프로메이드',
        title: '조립식 데크타일 우디&스토니&스타코&베니 / 월타일 모음',
        alt: '조립식 데크타일 우디&스토니&스타코&베니 / 월타일 모음',
        img: 'image/deal_promade.avif',
        price_rate: 50,
        price: 14900,
        average_score: 4.6,
        review_count: 27038,
    },
    {
        brand: '까사미아',
        title: '[5/5 원데이특가] 캄포 모듈형 패브릭 소파 (2인/3인/4인/코너형)',
        alt: '[5/5 원데이특가] 캄포 모듈형 패브릭 소파 (2인/3인/4인/코너형)',
        img: 'image/deal_kasa.avif',
        price_rate: "",
        price: 4130000,
        average_score: 4.8,
        review_count: 915,
    },
    {
        brand: '메종오브제',
        title: '[5/5단하루!15%쿠폰][1+1]화사한 컬러 파르베 커트러리 수저/디저트/양식기세트 모음',
        alt: '[5/5단하루!15%쿠폰][1+1]화사한 컬러 파르베 커트러리 수저/디저트/양식기세트 모음',
        img: 'image/deal_me.avif',
        price_rate: 33,
        price: 19900,
        average_score: 4.8,
        review_count: 29407,
    },
    {
        brand: '프로메이드',
        title: '[나혼산 진*희 사용] 공간 활용도가 뛰어난 페블 3단 60L 분리수거함 / 정리함',
        alt: '[나혼산 진*희 사용] 공간 활용도가 뛰어난 페블 3단 60L 분리수거함 / 정리함',
        img: 'image/deal_pro.avif',
        price_rate: 31,
        price: 26900,
        average_score: 4.7,
        review_count: 2348,
    },
    {
        brand: '셀인룸',
        title: 'diy 셀프 데코타일 접착식/비접착식 6장',
        title: 'diy 셀프 데코타일 접착식/비접착식 6장',
        img: 'image/deal_sel.jpg',
        price_rate: 19,
        price: 17900,
        average_score: 4.7,
        review_count: 24805,
    },
    {
        brand: '오랄비',
        title: '오랄비 칫솔 /치실 대용량 특가!',
        alt: '오랄비 칫솔 /치실 대용량 특가!',
        img: 'image/deal_oralb.avif',
        price_rate: 16,
        price: 24800,
        average_score: 4.7,
        review_count: 22859,
    },
    {
        brand: '디베라',
        title: '[오늘단하루] 24년형 차이슨 무선청소기 THE NEW 최대진공도43000PA',
        alt: '[오늘단하루] 24년형 차이슨 무선청소기 THE NEW 최대진공도43000PA',
        img: 'image/deal_di.avif',
        price_rate: 43,
        price: 159000,
        average_score: 4.9,
        review_count: 839,
    },
]

export const SpecialExhibition = [
    {
        title: '오픈런딜',
        alt: '오픈런딜',
        img: 'image/special_exhibition_open.jpeg',
        summery: '전상품 무료배송, 요일마다 바뀌는 파격특가 장보기!',
    },
    {
        title: '오직 여기선만, O!Goods',
        alt: '오직 여기선만, O!Goods',
        img: 'image/special_exhibition_save.png',
        summery: '오늘의집 큐레이션 편집샵 오!굿즈',
    },
    {
        title: '최대 25마원 SAVE!',
        alt: '영원한 특급패스, 오늘의집 배송!',
        img: 'image/special_exhibition_ogoods.jpg',
        summery: '0원한 특급패스, 오늘의집 배송!',
    },
]

export const BestItems = [
    {
        '전체': [
            {
                brand: '아엠홈',
                title: '[최대10%쿠폰+사은품][맞춤]비침없는 도톰 레이스/쉬폰커튼(나비주름/핀형/봉집)',
                alt: '[최대10%쿠폰+사은품][맞춤]비침없는 도톰 레이스/쉬폰커튼(나비주름/핀형/봉집)',
                img: 'image/best_all_aat.avif',
                price_rate: 28,
                price: 16800,
                average_score: 4.7,
                review_count: 35023,
            },
            {
                brand: '헬로우슬립',
                title: '[10%쿠폰] 부드러운 카스테라 워싱 항균 옥수수솜 간절기/사계절 차렵이불세트',
                alt: '[10%쿠폰] 부드러운 카스테라 워싱 항균 옥수수솜 간절기/사계절 차렵이불세트',
                img: 'image/best_all_hello.avif',
                price_rate: 37,
                price: 35900,
                average_score: 4.8,
                review_count: 36697,
            },
            {
                brand: '퀵슬립',
                title: 'Q4 유로탑 롤팩 매트리스 2size_적당푹신(롤팩)',
                alt: 'Q4 유로탑 롤팩 매트리스 2size_적당푹신(롤팩)',
                img: 'image/best_all_quick.avif',
                price_rate: 57,
                price: 299500,
                average_score: 4.8,
                review_count: 15949,
            },
        ],
        '여름맞이': [
            {
                brand: 'LG전자',
                title: '10만원할인 LG그램 16ZD90RU-GX56K/램16GB/256GB',
                alt: '10만원할인 LG그램 16ZD90RU-GX56K/램16GB/256GB',
                img: 'image/best_gift_lg1.avif',
                price_rate: 14,
                price: 1450000,
                average_score: 5,
                review_count: 80,
            },
            {
                brand: '코튼리빙',
                title: '[선착순28,405원]후기7만돌파! 40수 코마사 호텔수건 200g 10장',
                alt: '[선착순28,405원]후기7만돌파! 40수 코마사 호텔수건 200g 10장',
                img: 'image/best_living_coat.avif',
                price_rate: 62,
                price: 29900,
                average_score: 4.7,
                review_count: 70991,
            },
            {
                brand: 'LG전자',
                title: 'LG그램 17ZD90RU-GX56K 13세대 인텔i5 초고해상도 대화면 노트북',
                alt: 'LG그램 17ZD90RU-GX56K 13세대 인텔i5 초고해상도 대화면 노트북',
                img: 'image/best_gift_lg2.avif',
                price_rate: 24,
                price: 1399000,
                average_score: 5,
                review_count: 8,
            },
        ],
        '가구': [
            {
                brand: '한샘',
                title: '한샘몰pick 눕 데일리 구스 아쿠아텍스 패브릭 모듈 소파 4인용 4colors',
                alt: '한샘몰pick 눕 데일리 구스 아쿠아텍스 패브릭 모듈 소파 4인용 4colors',
                img: 'image/best_funi_gan.jpg',
                price_rate: 35,
                price: 724900,
                average_score: 4.7,
                review_count: "리뷰 3,426",
            },
            {
                brand: '수면밀도',
                title: '[5% 쿠폰] 허리 디스크 환자가 만든 코어 릴랙스 매트리스 S,SS,Q,K',
                alt: '[5% 쿠폰] 허리 디스크 환자가 만든 코어 릴랙스 매트리스 S,SS,Q,K',
                img: 'image/best_funi_su.avif',
                price_rate: 50,
                price: 299000,
                average_score: 4.7,
                review_count: 70991,
            },
            {
                brand: '웰퍼니처',
                title: '쿠폰+무료내림ㅣ허리엔 더매직 허리특화 포켓스프링 매트리스 S/SS/Q/K/SK',
                alt: '쿠폰+무료내림ㅣ허리엔 더매직 허리특화 포켓스프링 매트리스 S/SS/Q/K/SK',
                img: 'image/best_funi_well.jpg',
                price_rate: 47,
                price: 229000,
                average_score: 4.8,
                review_count: 9600,
            },
        ],
        '패브릭': [
            {
                brand: '헬로우슬립',
                title: '[10%쿠폰] 부드러운 카스테라 워싱 항균 옥수수솜 간절기/사계절 차렵이불세트',
                alt: '[10%쿠폰] 부드러운 카스테라 워싱 항균 옥수수솜 간절기/사계절 차렵이불세트',
                img: 'image/best_all_hello.avif',
                price_rate: 37,
                price: 35900,
                average_score: 4.8,
                review_count: 35698,
            },
            {
                brand: '아엠홈',
                title: '[최대10%쿠폰+사은품][맞춤]비침없는 도톰 레이스/쉬폰커튼(나비주름/핀형/봉집)',
                alt: '[최대10%쿠폰+사은품][맞춤]비침없는 도톰 레이스/쉬폰커튼(나비주름/핀형/봉집)',
                img: 'image/best_all_aat.avif',
                price_rate: 28,
                price: 16800,
                average_score: 4.8,
                review_count: 35023,
            },
            {
                brand: '데코지오',
                title: '[맞춤]브라우니 린넨 암막커튼 핀형/아일렛형/형상기억 33색상',
                alt: '[맞춤]브라우니 린넨 암막커튼 핀형/아일렛형/형상기억 33색상',
                img: 'image/best_feb_deco.avif',
                price_rate: 39,
                price: 19800,
                average_score: 4.6,
                review_count: 9948,
            },
        ],
        '가전・디지털': [
            {
                brand: '삼성전자',
                title: '혜택가49만원대 삼성 창문형에어컨 AW05B5171BWA 새틴블루',
                alt: '혜택가49만원대 삼성 창문형에어컨 AW05B5171BWA 새틴블루',
                img: 'image/best_digi_sam.jpg',
                price_rate: 34,
                price: 524000,
                average_score: 4.7,
                review_count: 224,
            },
            {
                brand: 'LG전자',
                title: '휘센 오브제 칸 FQ17HDKHC2 기본설치비포함/수도권충청경상강원',
                alt: '휘센 오브제 칸 FQ17HDKHC2 기본설치비포함/수도권충청경상강원',
                img: 'image/best_digi_lg.avif',
                price_rate: 11,
                price: 1778000,
                average_score: 4.8,
                review_count: 352,
            },
            {
                brand: '삼성전자',
                title: '인증점 삼성 Q9000 스탠드형 에어컨 AF17B6474TZS 기본설치포함',
                alt: '인증점 삼성 Q9000 스탠드형 에어컨 AF17B6474TZS 기본설치포함',
                img: 'image/best_digi_sam1.jpg',
                price_rate: 32,
                price: 1342000,
                average_score: 4.9,
                review_count: 224,
            },
        ],
        '주방용품': [
            {
                brand: '이브리영',
                title: '자동물빠짐 연마제없는 304 올스텐 2단 식기건조대+수저통+접시꽂이+도마걸이',
                alt: '자동물빠짐 연마제없는 304 올스텐 2단 식기건조대+수저통+접시꽂이+도마걸이',
                img: 'image/best_ki_eve.avif',
                price_rate: 56,
                price: 56900,
                average_score: 4.8,
                review_count: 3773,
            },
            {
                brand: '락앤락',
                title: '[브랜드위크] 단독 락앤락 탑클라스 내열유리 화이트 10개세트',
                alt: '[브랜드위크] 단독 락앤락 탑클라스 내열유리 화이트 10개세트',
                img: 'image/best_ki_rock.jpg',
                price_rate: 30,
                price: 54940,
                average_score: 4.8,
                review_count: 3048,
            },
            {
                brand: '트루쿡',
                title: '[리퍼] 1+1 국내생산 세라믹 IH 프라이팬&냄비 14종',
                alt: '[리퍼] 1+1 국내생산 세라믹 IH 프라이팬&냄비 14종',
                img: 'image/best_ki_true.avif',
                price_rate: 62,
                price: 29900,
                average_score: 4.6,
                review_count: 782,
            },
        ],
        '식품': [
            {
                brand: '오쏘몰',
                title: '[해외] 1+1 오쏘몰 이뮨 액상+정제 30일*2박스 (총60일)',
                alt: '[해외] 1+1 오쏘몰 이뮨 액상+정제 30일*2박스 (총60일)',
                img: 'image/best_food_osso.avif',
                price_rate: 27,
                price: 151000,
                average_score: 4.6,
                review_count: 1369,
            },
            {
                brand: '립톤',
                title: '아이스티 믹스 복숭아 1.5kg  8개',
                alt: '아이스티 믹스 복숭아 1.5kg  8개',
                img: 'image/best_food_lip.avif',
                price_rate: 28,
                price: 109000,
                average_score: 4.9,
                review_count: 724,
            },
            {
                brand: '매일유업',
                title: '[팩당 500원대] 매일두유 고단백 190ml 48팩',
                alt: '[팩당 500원대] 매일두유 고단백 190ml 48팩',
                img: 'image/best_food_mail.jpg',
                price_rate: 37,
                price: 30500,
                average_score: 4.6,
                review_count: 2236,
            },
        ],
        '데코・식물': [
            {
                brand: '헤트라스',
                title: '[1+1] 대용량 500ml  프리미엄 실내 디퓨저 방향제 +선물박스 +리드스틱',
                alt: '[1+1] 대용량 500ml  프리미엄 실내 디퓨저 방향제 +선물박스 +리드스틱',
                img: 'image/best_deco_het.gif',
                price_rate: 46,
                price: 18800,
                average_score: 4.8,
                review_count: 6894,
            },
            {
                brand: '에이센트',
                title: '[3+1] 네이처 디퓨저 200ml 실내방향제 집들이선물 그린에어리',
                alt: '[3+1] 네이처 디퓨저 200ml 실내방향제 집들이선물 그린에어리',
                img: 'image/best_deco_acent.avif',
                price_rate: 38,
                price: 8500,
                average_score: 4.8,
                review_count: 50910,
            },
            {
                brand: '무아스',
                title: '풀문 백라이트 무드등 LED 벽시계 탁상시계 집들이 신혼집 선물',
                alt: '풀문 백라이트 무드등 LED 벽시계 탁상시계 집들이 신혼집 선물',
                img: 'image/best_deco_mu.jpg',
                price_rate: 4,
                price: 84800,
                average_score: 4.7,
                review_count: 906,
            },
        ], 
        '조명': [
            {
                brand: '아우어룸',
                title: '[스마트전구증정] 머쉬룸 장스탠드 순수 국내자체제작 조명 _7colors',
                alt: '[스마트전구증정] 머쉬룸 장스탠드 순수 국내자체제작 조명 _7colors',
                img: 'image/best_light_our.avif',
                price_rate: 15,
                price: 129000,
                average_score: 4.8,
                review_count: 7921,
            },
            {
                brand: '스피아룸',
                title: '[홀리스 스윙 장스탠드 조명_2colors (LED전구 증정)',
                alt: '[홀리스 스윙 장스탠드 조명_2colors (LED전구 증정)',
                img: 'image/best_light_spi.avif',
                price_rate: 17,
                price: 75900,
                average_score: 4.8,
                review_count: 1373,
            },
            {
                brand: '레나에너지',
                title: '단독컬러출시! 북유럽 플로어 장스탠드 LED 거실등 조명 3colors(리모컨 옵션)',
                alt: '단독컬러출시! 북유럽 플로어 장스탠드 LED 거실등 조명 3colors(리모컨 옵션)',
                img: 'image/best_light_rena.jpg',
                price_rate: 58,
                price: 29800,
                average_score: 4.8,
                review_count: 2729,
            },
        ],        
        '수납・정리': [
            {
                brand: '상도가구',
                title: '사이즈 맞춤제작 몬스터랙 조립식 앵글 모듈 공간활용 수납선반 팬트리',
                alt: '사이즈 맞춤제작 몬스터랙 조립식 앵글 모듈 공간활용 수납선반 팬트리',
                img: 'image/best_sto_sang.avif',
                price_rate: 33,
                price: 19900,
                average_score: 4.6,
                review_count: 8876,
            },
            {
                brand: '아이리스코리아',
                title: '1+1 수비르 서랍장 슬라이딩 리빙박스 옷장 정리 7size',
                alt: '1+1 수비르 서랍장 슬라이딩 리빙박스 옷장 정리 7size',
                img: 'image/best_sto_iris.avif',
                price_rate: 33,
                price: 17200,
                average_score: 4.6,
                review_count: 13335,
            },
            {
                brand: '진심감성(가구)',
                title: '논슬립 어깨뿔방지 옷걸이 30개 5colors (니트/정장/맨투맨)',
                alt: '논슬립 어깨뿔방지 옷걸이 30개 5colors (니트/정장/맨투맨)',
                img: 'image/best_sto_none.jpg',
                price_rate: 62,
                price: 18900,
                average_score: 4.8,
                review_count: 13090,
            },
        ],
        '생활용품': [
            {
                brand: '코튼리빙',
                title: '[선착순28,405원]후기7만돌파! 40수 코마사 호텔수건 200g 10장',
                alt: '[선착순28,405원]후기7만돌파! 40수 코마사 호텔수건 200g 10장',
                img: 'image/best_living_coat.avif',
                price_rate: 62,
                price: 29900,
                average_score: 4.7,
                review_count: 70992,
            },
            {
                brand: '다룸',
                title: '1+1 수비르 서랍장 슬라이딩 리빙박스 옷장 정리 7size',
                alt: '1+1 수비르 서랍장 슬라이딩 리빙박스 옷장 정리 7size',
                img: 'image/best_living_da.jpg',
                price_rate: 28,
                price: 35600,
                average_score: 4.7,
                review_count: 2027,
            },
            {
                brand: '프로메이드',
                title: '논슬립 어깨뿔방지 옷걸이 30개 5colors (니트/정장/맨투맨)',
                alt: '논슬립 어깨뿔방지 옷걸이 30개 5colors (니트/정장/맨투맨)',
                img: 'image/best_living_grande.avif',
                price_rate: 45,
                price: 47500,
                average_score: 4.6,
                review_count: 5921,
            },
        ],
        '생필품': [
            {
                brand: '배배숲',
                title: '시그니처레드70매캡20팩',
                alt: '시그니처레드70매캡20팩',
                img: 'image/best_daily_bebe.jpg',
                price_rate: 34,
                price: 31990,
                average_score: 4.9,
                review_count: 1980,
            },
            {
                brand: '헤드앤숄더',
                title: '샴푸 850ml x 3개 + 미니샴푸 3개',
                alt: '샴푸 850ml x 3개 + 미니샴푸 3개',
                img: 'image/best_daily_head.jpg',
                price_rate: 37,
                price: 31000,
                average_score: 4.8,
                review_count: 3374,
            },
            {
                brand: '크리넥스',
                title: '3겹 데코&소프트 수딩플러스 (27Mx24롤)x2백',
                alt: '3겹 데코&소프트 수딩플러스 (27Mx24롤)x2백',
                img: 'image/best_daily_cre.avif',
                price_rate: 17,
                price: 41200,
                average_score: 4.8,
                review_count: 670,
            },
        ],
        '유아・아동': [
            {
                brand: '배배숲',
                title: '시그니처레드70매캡20팩',
                alt: '시그니처레드70매캡20팩',
                img: 'image/best_daily_bebe.jpg',
                price_rate: 34,
                price: 31990,
                average_score: 4.9,
                review_count: 1980,
            },
            {
                brand: '뉴트리시아',
                title: '[해외] 압타밀 프로푸트라 800g 6팩(1단계/2단계/프레/킨더밀쉬)',
                alt: '[해외] 압타밀 프로푸트라 800g 6팩(1단계/2단계/프레/킨더밀쉬)',
                img: 'image/best_baby_new.avif',
                price_rate: 36,
                price: 216000,
                average_score: 4.8,
                review_count: 260,
            },
            {
                brand: '팸퍼스',
                title: '2024 에어차차 썸머팬티 2박스 5단계 6팩 312매',
                alt: '2024 에어차차 썸머팬티 2박스 5단계 6팩 312매',
                img: 'image/best_baby_pam.jpg',
                price_rate: "",
                price: 193500,
                average_score: 4.8,
                review_count: 6,
            },
        ],
        '반려동물': [
            {
                brand: '로하우스',
                title: '[12%쿠폰]미끄럼방지 애견매트 논슬립 펫 강아지 고양이 롤매트',
                alt: '[12%쿠폰]미끄럼방지 애견매트 논슬립 펫 강아지 고양이 롤매트',
                img: 'image/best_pet_ro.avif',
                price_rate: 23,
                price: 9900,
                average_score: 4.7,
                review_count: 1839,
            },
            {
                brand: '세븐펫',
                title: '11+1/17+1 타일카페트 셀프인테리어 강아지 도톰매트 그란데(50x50/60x60)',
                alt: '11+1/17+1 타일카페트 셀프인테리어 강아지 도톰매트 그란데(50x50/60x60)',
                img: 'image/best_pet_seven.avif',
                price_rate: 19,
                price: 56900,
                average_score: 4.7,
                review_count: 1210,
            },
            {
                brand: '로본소',
                title: '[리퍼]신규컬러 입고!pvc 강아지 미끄럼방지 롤매트 두께 6mm',
                alt: '[리퍼]신규컬러 입고!pvc 강아지 미끄럼방지 롤매트 두께 6mm',
                img: 'image/best_pet_repo.avif',
                price_rate: 19,
                price: 9700,
                average_score: 4.7,
                review_count: 1489,
            },
        ],
        '캠핑・레저': [
            {
                brand: '지라프',
                title: '구이바다 세라믹 아이보리에디션 M',
                alt: '구이바다 세라믹 아이보리에디션 M',
                img: 'image/best_camp_jira.avif',
                price_rate: 22,
                price: 139000,
                average_score: 4.8,
                review_count: 2284,
            },
            {
                brand: '제백',
                title: '샴푸 850ml x 3개 + 미니샴푸 3개',
                alt: '샴푸 850ml x 3개 + 미니샴푸 3개',
                img: 'image/best_camp_je.avif',
                price_rate: 50,
                price: 199000,
                average_score: 4.8,
                review_count: 666,
            },
            {
                brand: '마이크로킥보드',
                title: '3겹 데코&소프트 수딩플러스 (27Mx24롤)x2백',
                alt: '3겹 데코&소프트 수딩플러스 (27Mx24롤)x2백',
                img: 'image/best_camp_my.jpg',
                price_rate: 3,
                price: 233770,
                average_score: 4.8,
                review_count: 13,
            },
        ],
        '공구DIY': [
            {
                brand: '매직픽스',
                title: '바닥 데코타일 로뎀 50cm(13장/1박스)18colors',
                alt: '바닥 데코타일 로뎀 50cm(13장/1박스)18colors',
                img: 'image/best_diy_magi.avif',
                price_rate: 14,
                price: 35100,
                average_score: 4.7,
                review_count: 3444,
            },
            {
                brand: '프로메이드',
                title: '마감재/신규색상 출시! 조립식 데크타일 - 스토니(Stony) 36P',
                alt: '마감재/신규색상 출시! 조립식 데크타일 - 스토니(Stony) 36P',
                img: 'image/best_diy_pro.avif',
                price_rate: 49,
                price: 50900,
                average_score: 4.7,
                review_count: 7988,
            },
            {
                brand: '도돈',
                title: '접착식 감성 바닥 데코타일 뚝딱타일 50cm(9colors)',
                alt: '접착식 감성 바닥 데코타일 뚝딱타일 50cm(9colors)',
                img: 'image/best_diy_dodon.avif',
                price_rate: 16,
                price: 22500,
                average_score: 4.8,
                review_count: 1227,
            },
        ],
        '인테리어시공': [
            {
                brand: '워터클린',
                title: '[얼리버드특가] 에어컨 청소 클리닝 서비스 (구매 후 예약필수 상품)',
                alt: '[얼리버드특가] 에어컨 청소 클리닝 서비스 (구매 후 예약필수 상품)',
                img: 'image/best_inte_water.avif',
                price_rate: 21,
                price: 50900,
                average_score: 4.9,
                review_count: 2123,
            },
            {
                brand: '문장군',
                title: '[단독] 아파트중문 현관 3연동중문 무료방문실측 직영시공',
                alt: '[단독] 아파트중문 현관 3연동중문 무료방문실측 직영시공',
                img: 'image/best_inte_moon.avif',
                price_rate: 44,
                price: 490000,
                average_score: 4.9,
                review_count: 2074,
            },
            {
                brand: '메리메이드',
                title: '안심 에어컨 분해청소 (벽걸이/스탠드/천정형)',
                alt: '안심 에어컨 분해청소 (벽걸이/스탠드/천정형)',
                img: 'image/best_inte_me.avif',
                price_rate: 21,
                price: 84800,
                average_score: 4.7,
                review_count: 5491,
            },
        ],
        '렌탈・구독': [
            {
                brand: 'sk매직',
                title: '[렌탈] 24년형NEW 원코크 얼음물 정수기 WPU-IAC414',
                alt: '[렌탈] 24년형NEW 원코크 얼음물 정수기 WPU-IAC414',
                img: 'image/best_rental_sk.jpg',
                price_rate: '',
                price: '',
                average_score: '',
                review_count: '',
            },
            {
                brand: '삼성전자',
                title: '[렌탈] 비스포크 4도어 냉장고 905L 메탈 멜로우 화이트 RF90DG90124W',
                alt: '[렌탈] 비스포크 4도어 냉장고 905L 메탈 멜로우 화이트 RF90DG90124W',
                img: 'image/best_rental_sam1.jpeg',
                price_rate: '',
                price: '',
                average_score: '',
                review_count: '',
            },
            {
                brand: '삼성전자',
                title: '[렌탈] 비스포크 4도어 냉장고 905L 매트 크리미 베이지 RF90DG90124E',
                alt: '[렌탈] 비스포크 4도어 냉장고 905L 매트 크리미 베이지 RF90DG90124E',
                img: 'image/best_rental_sam2.jpeg',
                price_rate: '',
                price: '',
                average_score: '',
                review_count: '',
            },
        ],
        '장보기': [
            {
                brand: '코튼리빙',
                title: '[선착순28,405원]후기7만돌파! 40수 코마사 호텔수건 200g 10장',
                alt: '[선착순28,405원]후기7만돌파! 40수 코마사 호텔수건 200g 10장',
                img: 'image/best_living_coat.avif',
                price_rate: 62,
                price: 29900,
                average_score: 4.7,
                review_count: 70993,
            },
            {
                brand: '오쏘몰',
                title: '[해외] 1+1 오쏘몰 이뮨 액상+정제 30일*2박스 (총60일)',
                alt: '[해외] 1+1 오쏘몰 이뮨 액상+정제 30일*2박스 (총60일)',
                img: 'image/best_food_osso.avif',
                price_rate: 24,
                price: 151000,
                average_score: 4.6,
                review_count: 1369,
            },
            {
                brand: '배배숲',
                title: '시그니처레드70매캡20팩',
                alt: '시그니처레드70매캡20팩',
                img: 'image/best_daily_bebe.jpg',
                price_rate: 34,
                price: 31990,
                average_score: 4.9,
                review_count: 1980,
            },
        ],
        '혼수・신혼': [
            {
                brand: '삼성전자',
                title: '혜택가49만원대 삼성 창문형에어컨 AW05B5171BWA 새틴블루',
                alt: '혜택가49만원대 삼성 창문형에어컨 AW05B5171BWA 새틴블루',
                img: 'image/best_digi_sam1.jpg',
                price_rate: 44,
                price: 524000,
                average_score: 4.7,
                review_count: 224,
            },
            {
                brand: '헬로우슬립',
                title: '[10%쿠폰] 부드러운 카스테라 워싱 항균 옥수수솜 간절기/사계절 차렵이불세트',
                alt: '[10%쿠폰] 부드러운 카스테라 워싱 항균 옥수수솜 간절기/사계절 차렵이불세트',
                img: 'image/best_all_hello.avif',
                price_rate: 37,
                price: 35900,
                average_score: 4.8,
                review_count: 35700,
            },
            {
                brand: '한샘',
                title: '[10%쿠폰] 부드러운 카스테라 워싱 항균 옥수수솜 간절기/사계절 차렵이불세트',
                alt: '[10%쿠폰] 부드러운 카스테라 워싱 항균 옥수수솜 간절기/사계절 차렵이불세트',
                img: 'image/best_funi_gan.jpg',
                price_rate: 35,
                price: 724900,
                average_score: 4.7,
                review_count: 3426,
            },
        ],
    }
]

export const CarouselImgArr = [
    {
        img: 'image/carousel_1.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_2.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_3.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_4.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_5.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_6.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_7.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_8.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_9.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_10.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_11.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_12.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_13.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_14.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_15.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_16.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_17.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_18.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_19.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_20.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
    {
        img: 'image/carousel_21.avif',
        alt: '웰퍼니처 인기가구 세일'
    },
]